In [8]:
range(0,10)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
x = range(10,20)

In [12]:
x[1:3]

[11, 12]

In [23]:
#def sq(x):
 #   return x ** 2

print map(lambda x: x^2, range(10))

[-9, -8, -7, -6, -5, -4, -3, -2, -1, 0]


In [24]:
?set

In [25]:
?int

In [33]:
int('0b110', base=0)

6

In [40]:
x = True

In [41]:
x = 5

In [42]:
print x

5


In [64]:
x = [1, 2, 3]
y = x
id(x)
print(x is y)
print(x is [1, 2, 3])
print(y is [1, 2, 3])

True
False
False


In [48]:
x = tuple()

In [49]:
print x

()


# data upload

In [56]:
#file_obj = open('/Users/nazirdashtiev/iPythonProjects/test.rtf','r')

In [15]:
file_obj = open('test2.txt','r')
print file_obj.read()

1. Hello there!
2. Привет человек!
3.
4. Какой-то текст.
5. 
6. Another text in english.
7. And some numbers - 0, 1, 2, 3.



In [16]:
file_obj = open('test2.txt','r')
print file_obj.readline()

1. Hello there!



In [17]:
file_obj = open('test2.txt','r')
for line in file_obj: print line.strip()

1. Hello there!
2. Привет человек!
3.
4. Какой-то текст.
5.
6. Another text in english.
7. And some numbers - 0, 1, 2, 3.


In [19]:
file_obj = open('test2.txt','r')
data_list = list(file_obj)
for line in data_list: print line.strip()

1. Hello there!
2. Привет человек!
3.
4. Какой-то текст.
5.
6. Another text in english.
7. And some numbers - 0, 1, 2, 3.


In [20]:
f = open('test2.txt','r')
print "".join(f.readlines()[2:5])

3.
4. Какой-то текст.
5. 



In [21]:
f = open('test2.txt','r')
i = 0
for line in f:
    if i>=2 and i<5:
        print line,
    i += 1

3.
4. Какой-то текст.
5. 


In [23]:
file_obj = open('test2.txt','r')
file_obj.close()
file_obj.read()

ValueError: I/O operation on closed file

In [24]:
file_obj = open('test.rtf','r')
print file_obj.read()

{\rtf1\ansi\ansicpg1252\cocoartf1404\cocoasubrtf470
{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 Hello sir!\
\uc0\u1055 \u1088 \u1080 \u1074 \u1077 \u1090 , \u1090 \u1086 \u1074 \u1072 \u1088 \u1080 \u1065 !}


# Codecs

In [26]:
import codecs

In [34]:
file_obj = codecs.open('test.rtf','r', coding='utf-8')
print file_obj.read()

TypeError: open() got an unexpected keyword argument 'coding'

In [35]:
file_obj = open('write_new_file.txt', 'w')
string = 'какой-то текст\n'
file_obj.write(string)
file_obj.close()

In [36]:
!cat write_new_file.txt

какой-то текст


In [7]:
list = (1, 'stop', True)
print list
type(list)

(1, 'stop', True)


tuple

In [8]:
tel = {'jack': 4098, 'sape': 4139}

In [9]:
print tel

{'sape': 4139, 'jack': 4098}


In [12]:
tel = {'jack': 4098, 'sape': 4139, 1: 'sad', 'gordano': True}

In [13]:
print tel

{'sape': 4139, 'gordano': True, 'jack': 4098, 1: 'sad'}


In [22]:
x = range(10)
print x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [46]:
x = xrange(0, 10, 7)
print x

xrange(0, 14, 7)


In [38]:
?range

In [59]:
f = lambda x, y: x ** 2
f(3, 4534)

9

In [65]:
def f(x):
    return x**2
    
f(3)

9


In [66]:
import pandas as pd

In [68]:
frame = pd.DataFrame({'numbers': range(10), 'chars': ['a']*10})

In [69]:
frame

chars  numbers
0     a        0
1     a        1
2     a        2
3     a        3
4     a        4
5     a        5
6     a        6
7     a        7
8     a        8
9     a        9

In [73]:
frame = pd.read_csv('/Users/nazirdashtiev/Downloads/bRhsYYCCg4.csv', header=0, sep=',')

In [74]:
frame

driver_uuid  city_id  supply_hours  \
0      7a8b702c-b1e1-4c60-8501-615f8d1b5f63      145     63.270000   
1      0c56d0d1-35bb-41f1-8c25-17244ecbd804      145      9.790000   
2      4c898dbe-5b1d-42e4-8335-6ad7a05c93d8      145     34.977500   
3      50030d88-89c4-4cb8-9dc5-cf736d7a926f      145      5.685000   
4      ff7e36fd-cc0f-4cd5-8f39-483078da2979      145      1.770000   
5      7534a4f2-6f9c-4149-90c3-7cb8e23a2854      145     40.280000   
6      45602567-2f4a-4f5e-aa2f-4e95af675a95      145     16.936667   
7      643e76d8-d381-490a-8b59-f8d1788f8ad4      145     30.310000   
8      edcf3f27-ca7b-43f9-825a-f8818a2288ff      145     54.660000   
9      b7f78f06-d5e8-4ed1-822a-a059f33a2ef9      145      9.050000   
10     680d2f26-6f30-48d6-9caf-e8aa929e9f38      145     17.883333   
11     b157c6de-dd8a-488b-a344-982e82ee61d3      145     52.995000   
12     4175dbd4-7975-4d04-be78-2361b8a114aa      145      5.650000   
13     b1534d4a-be9d-42cf-b743-136ac8cc7d0f      145     40.525000   
14     102655b7-a74c-4e1a-8e60-516b8d6fa7a5      145     16.836667   
15     4a0ae255-198a-41d0-bb1c-d75aa4097736      145      3.420000   
16     56593f9c-b132-49e5-a18d-92b71a04ac0f      145     93.910000   
17     44e70392-93af-4cf6-8f13-9225d9f766c7      145     43.842500   
18     85ba0348-a43a-4fe4-a894-cc71d403970e      145     28.570000   
19     87a0b825-349a-42a4-95b3-12bd4e7151ed      145     19.392500   
20     6a9c1d0d-09c7-49d4-84db-256c4ad5a88d      145      5.333333   
21     53ecbae2-0387-4873-9d8a-46fbdb2cf285      145      1.290000   
22     5500ef82-9701-43ab-a5e8-d4cc5d688b9b      145     25.960000   
23     c19d112f-c789-413f-a55e-16e01722852c      145      5.085000   
24     43a90564-cba7-412e-a654-2ce77617b9ce      145     14.197500   
25     efc38fc3-cb64-47c4-b461-09e1f6ce5486      145     35.330000   
26     00bbab02-b856-4287-bae9-baa00610f1b0      145     29.542500   
27     e450554b-2f2b-46a2-9d92-0a37d315e956      145     27.067500   
28     49919e6f-9439-4f76-9d51-01facd85b84f      145      2.060000   
29     33c65df2-a63c-4d8f-bcc3-f00b5bf5bb7e      145     27.065000   
...                                     ...      ...           ...   
27368  0eabc703-6f96-4292-a4ef-928a3ae89e91      145     53.813333   
27369  941856fe-c6ba-43b1-b40e-e6fdd4a358be      145      8.816667   
27370  c4e0a430-3bdf-4096-a00c-05754e7abd9c      145      8.920000   
27371  772c97f8-0831-4925-88d0-05448487b0e8      145     11.425000   
27372  227ad9d8-97e9-49cd-a893-8ee889c7bf3b      145     46.830000   
27373  beb5afa7-d240-44c2-b3f5-184fbc49e562      145     64.445000   
27374  7059e8b9-93da-4adf-9105-fd54e7dd3035      145      7.740000   
27375  7bb46eae-c3ca-48b4-9a83-a669955dbc67      145     11.085000   
27376  7fd7a4b2-073b-46b5-bcd1-5b5ba3c8a49b      145     37.735000   
27377  6468215f-590d-4b0c-abc1-ca843f142496      145      4.890000   
27378  09570dd1-f324-49dc-8fd6-445d648874c4      145     19.820000   
27379  a9f3d3ca-8ff9-4981-9a1c-5953b879e616      145      3.036667   
27380  35ec9c74-db7e-4da2-a99a-88378c3067b5      145     46.645000   
27381  204941d6-54ee-41b6-b8f3-f5158842b684      145     15.460000   
27382  a094def0-b22f-4587-8252-a91b8b889a4f      145      0.120000   
27383  e20466e2-a7c3-4083-82a0-94784142d91b      145     22.825000   
27384  2994d6ea-3bcf-4bab-a0e5-5b34d9ccbcf7      145      9.895000   
27385  701754ba-a0d8-4cde-852d-d50c643053cd      145     18.630000   
27386  8a4c166b-db74-4373-8142-01cb402c4a6f      145     12.150000   
27387  4c6a3b5e-fd3a-4363-a8bd-96ac0a9e67b4      145      0.620000   
27388  d7daaed4-d244-4453-b5ba-a70df8dd6c76      145     45.695000   
27389  19eadd48-0faa-440c-8e90-d6141d2469bf      145     14.330000   
27390  890cf259-0657-41e2-8593-91644a4bff79      145      1.120000   
27391  180c58bb-24d8-434e-bd8a-243f3b4c91af      145     46.650000   
27392  a7a1b69d-32df-4fa5-ad13-f22bee20c7ca      145     46.030000   
27393  ede66ad2-2c5d-48b4-96da-20ba81984fa

In [97]:
frame2 = pd.DataFrame({})
#frame2["col1"] = True, False, False
frame2.addColumn('col2',[True, False, True])

AttributeError: 'DataFrame' object has no attribute 'addColumn'

In [94]:
frame2

col1
0   True
1  False
2  False

In [105]:
import numpy as np

In [108]:
np.arange(1, 101, 40)

array([ 1, 41, 81])

In [110]:
np.random.rand(4, 5) 

array([[ 0.01347222,  0.40285088,  0.65847357,  0.66276356,  0.63541423],
       [ 0.66931391,  0.32570128,  0.45701456,  0.60843957,  0.48034701],
       [ 0.48485117,  0.93700966,  0.92097847,  0.85773154,  0.66979611],
       [ 0.25039322,  0.24290162,  0.14053903,  0.74057804,  0.72863793]])

In [111]:
?optimize.minimize

Object `optimize.minimize` not found.


In [113]:
x = np.array([[1, 2, 3], [4, 5, 6]])

In [114]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [127]:
x[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [133]:
frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27398 entries, 0 to 27397
Data columns (total 11 columns):
driver_uuid            27398 non-null object
city_id                27398 non-null int64
supply_hours           27397 non-null float64
avg_daily_shifts       27397 non-null float64
median_daily_shifts    27397 non-null float64
weekly_shifts          27397 non-null float64
trips                  27398 non-null float64
gross_bookings         27398 non-null float64
commission             27398 non-null float64
incentives             20078 non-null float64
earnings               27398 non-null float64
dtypes: float64(9), int64(1), object(1)
memory usage: 2.3+ MB


In [140]:
f = np.array([1, True, 'smth'])
print f

['1' 'True' 'smth']
